#!/usr/bin/env zsh

# This file is sourced from ../runcom/zshrc

# Exports environment variables defined in a .env or .localenv file
function setenv() {
  if [ -f .env ]; then
    export $(cat .env | xargs)
  fi
  if [ -f .localenv ]; then
    export $(cat .localenv | xargs)
  fi
}

# Generate random characters and export it
function randomness() {
  export RANDOMNESS=$(openssl rand -base64 10)
}

# Switch and create tmux sessions from inside of other sessions
function tm() {
  [[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"
  if [ $1 ]; then
     tmux $change -t "$1" 2>/dev/null || (tmux new-session -d -s $1 && tmux $change -t "$1"); return
  fi
  session=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | fzf --exit-0) &&  tmux $change -t "$session" || echo "No sessions found."
}

# Easily connect to postgress instances with pg_service.conf
function pg() {
  if [ $1 ]; then
    PGSERVICE=$1 pgcli
  else
    echo 'A valid service name is required for this function'
  fi
}

function aws_login() {
  saml2aws login --session-duration 43200 --username ahayter@kyruus.com --duo-mfa-option="Duo Push" --skip-prompt
}
