#!/usr/bin/env zsh

# Generate ctags for entire python environment and project directory

function pytags() {
  ctags -R --fields=+l --languages=python -f ./tags \
    $(python -c "import os, sys; print(' '.join('{}'.format(d) for d in sys.path if os.path.isdir(d)))") .
}
