#!/usr/bin/env zsh

# This file is sourced from ../runcom/zshenv

# Setup path
path=(
$path
/usr/local/sbin
$HOME/.pyenv
$HOME/.cargo/bin
$HOME/.fnm
$HOME/.yarn/bin
$HOME/.config/yarn/global/node_modules/.bin
$HOME/Library/Python/2.7/bin
)

# Ensure path arrays do not contain duplicates
typeset -gU cdpath fpath mailpath path

