#!/usr/bin/env zsh

# This file is sourced from ../runcom/zshrc

rvm() {
  unset -f rvm
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
  rvm "$@"
}

