#!/usr/bin/env zsh

# prezto options
zstyle ':prezto:module:*' color 'yes'
zstyle ':prezto:module:*' case-sensitive 'no'
zstyle ':prezto:module:editor' key-bindings 'vi'
zstyle ':prezto:module:syntax-highlighting' styles \
	  'alias' 'fg=blue' \
	  'builtin' 'fg=blue' \
	  'command' 'fg=blue' \
	  'function' 'fg=blue' \
	  'precommand' 'fg=cyan' \
	  'commandseparator' 'fg=green'

# Source zplug
source $HOME/.zplug/init.zsh

zplug "modules/environment", from:prezto, defer:0

# prompt
zplug "bhilburn/powerlevel9k", at:zsh-async-integration, use:powerlevel9k.zsh-theme


zplug "modules/directory", from:prezto
zplug "modules/editor", from:prezto
zplug "modules/git", from:prezto
zplug "modules/tmux", from:prezto
zplug "modules/history", from:prezto
zplug "modules/spectrum", from:prezto

zplug "modules/osx", from:prezto
zplug "modules/terminal", from:prezto
zplug "modules/utility", from:prezto
zplug "modules/completion", from:prezto, defer:1

zplug "modules/syntax-highlighting", from:prezto, defer:2
zplug "modules/history-substring-search", from:prezto, defer:3

zplug load

