#!/usr/bin/env zsh

# This file is sourced (first) on all invocations of the shell, unless the -f option is set. It should
# contain commands to set the command search path, plus other important environment variables.
# Should not contain commands that produce output or assume the shell is attached to a tty.

# OS
if [ "$(uname -s)" = "Darwin" ]; then
  OS="macOS"
else
  OS=$(uname -s)
fi

# Resolve DOTFILES_DIR
# (assuming ~/settings/dotfiles on distros without readlink and/or $BASH_SOURCE/$0)
READLINK=$(which greadlink || which readlink)
CURRENT_SCRIPT=${(%):-%x}

if [[ -n $CURRENT_SCRIPT && -x "$READLINK" ]]; then
  SCRIPT_PATH=$($READLINK -f "$CURRENT_SCRIPT")
  DOTFILES_DIR=$(dirname "$(dirname "$SCRIPT_PATH")")
elif [ -d "$HOME/settings/dotfiles" ]; then
  DOTFILES_DIR="$HOME/settings/dotfiles"
else
  echo "Unable to find dotfiles, exiting."
  return
fi

# Cleanup
unset READLINK CURRENT_SCRIPT SCRIPT_PATH DOTFILE

# Source remaining environment from external files
for DOTFILE in "$DOTFILES_DIR"/system/{env,path}; do
  [ -f "$DOTFILE" ] && . "$DOTFILE"
done

# pyenv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi

# Export
export OS DOTFILES_DIR
