#!/usr/bin/env zsh

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# OS
if [ "$(uname -s)" = "Darwin" ]; then
  OS="macOS"
else
  OS=$(uname -s)
fi

# Resolve DOTFILES_DIR
# (assuming ~/settings/dotfiles on distros without readlink and/or $BASH_SOURCE/$0)

READLINK=$(which greadlink || which readlink)
CURRENT_SCRIPT=${(%):-%x}

if [[ -n $CURRENT_SCRIPT && -x "$READLINK" ]]; then
  SCRIPT_PATH=$($READLINK -f "$CURRENT_SCRIPT")
  DOTFILES_DIR=$(dirname "$(dirname "$SCRIPT_PATH")")
elif [ -d "$HOME/settings/dotfiles" ]; then
  DOTFILES_DIR="$HOME/settings/dotfiles"
else
  echo "Unable to find dotfiles, exiting."
  return
fi

# Source dotfiles (order matters)
POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=false
for DOTFILE in "$DOTFILES_DIR"/system/{function,function_*,env,prompt,nvm,rvm,zplug,alias}; do
  [ -f "$DOTFILE" ] && . "$DOTFILE"
done

# Cleanup
unset READLINK CURRENT_SCRIPT SCRIPT_PATH DOTFILE

# Export
export OS DOTFILES_DIR


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
