#!/usr/bin/env zsh

# Runs after zshenv

# Source dotfiles, $DOTFILES_DIR set in .zshenv (order matters)
for DOTFILE in "$DOTFILES_DIR"/system/{function,function_*,prompt,nvm,rvm,zplug,alias}; do
  [ -f "$DOTFILE" ] && . "$DOTFILE"
done

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -x "$(command -v pipenv)" ] && eval "$(env _PIPENV_COMPLETE=source-zsh pipenv)"
[ -f ~/src/svm/svm.sh ] && source ~/src/svm/svm.sh
[ -f ~/usr/local/bin/virtualenvwrapper.sh ] && source ~/usr/local/bin/virtualenvwrapper.sh
[ -f  ~/Library/Python/2.7/bin/virtualenvwrapper.sh ] && source ~/Library/Python/2.7/bin/virtualenvwrapper.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# fnm
eval "`fnm env`"

# pyenv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi
